---
title: "Workflow validation"
author: "Molecular Diagnostic Unit -- University Hospital Basel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  diroi: ''
editor_options: 
  chunk_output_type: console
---

```{r comparisons, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(magrittr)
diroi = params$diroi
```


```{r function, include=FALSE}
## FUNCTIONS
extract_parameters_from_dirname = function(watchdog_dirpath){
  mod_path = gsub("-",'_',watchdog_dirpath)
  rec = stringr::str_split(mod_path, pattern ="_", simplify = FALSE)[[1]]
  rec = rec[1:4]
  parameters = data.frame(name = watchdog_dirpath,
                            pcr_id = rec[1],
                            Bno = rec[2],
                          panel = rec[3],
                          wf_version = rec[4])
  return(parameters)
}

dload_DT = function(data_table){
  data_table %>%
  DT::datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(25,50,-1),
                                             c(25,50,"All"))))
}
extract_chr = function(locusstring){
  chr = stringr::str_extract(locusstring, pattern = 'chr.+?(?=:)')
  return(chr)
}
 
extract_start = function(locusstring){
  start = stringr::str_extract(locusstring, pattern = '(?<=chr.{1,2}:)\\d+')
  start = as.numeric(start)
return(start)
}

return_discordant_coordinates = function(input_file, subset_table){
  toi = subset(input_file, uid %in% subset_table$uid)
  toi = dplyr::select(toi, locus, filepath)
  toi$chr = extract_chr(toi$locus)
  toi$start = extract_start(toi$locus)
  toi$end = extract_start(toi$locus)
  toi = dplyr::relocate(toi, chr, start, end)
  toi = dplyr::select(toi, -locus)
  return(toi)
}
join_parameters_and_res = function(results_table){
  results_table = dplyr::filter(results_table, !is.na(value))
  parameters = dplyr::bind_rows(lapply(results_table$name, extract_parameters_from_dirname))
  joined_table = dplyr::left_join(results_table, parameters) 
  joined_table = dplyr::distinct(joined_table)
  return(joined_table)
}
count_variant_wf_version = function(parameter_table){
  parameter_table = dplyr::select(parameter_table,-name,-locus) %>%
  dplyr::group_by(chr, start, end,gene,coding,amino_acid_change,wf_version) %>%
  dplyr::count(sort = TRUE) %>%
  tidyr::pivot_wider(names_from = wf_version,
                     values_from = n)
  return(parameter_table)
}

remove_na_entries = function(res_list){
  res_table = dplyr::bind_rows(res_list[!is.na(res_list)])
  return(res_table)
}

add_coordinates = function(res_table){
  res_table = tidyr::separate(res_table, col = 'uid', into = c('gene','coding','amino_acid_change','locus'),sep = "__", remove = FALSE)
  res_table$chr = extract_chr(res_table$locus)
  res_table$end = extract_start(res_table$locus)
  res_table$start = extract_start(res_table$locus)
  res_table = dplyr::relocate(res_table, chr, start, end)
  return(res_table)
}
snv_read = function(filepath){
  foi = readr::read_tsv(filepath)
  foi = tidyr::unite(foi, col = 'uid', c(gene,coding,amino_acid_change,locus), remove = FALSE, sep = "__")
  foi$filepath = filepath
  foi = dplyr::relocate(foi, percent_frequency)
  base_name = basename(dirname(unique(foi$filepath)))
  foi$name = base_name
  return(foi)
}


```

## Aggregate file comparisons by directory structure
```{r}
#diroi = paste0('/Users/manzo/USB/USB_Diagnostics/workflow_validation/', "/OCAPlus")
#diroi = getwd()
preps = list.files(path = diroi, pattern = "prep_snv.txt", recursive = TRUE, full.names = TRUE)

```


```{r, include=TRUE}
read_input_tsv = function(prep_snvs){
  dir_name = dirname(prep_snvs)
  tsvs = list.files(path = dir_name, pattern = ".*.tsv", full.names = TRUE)
  base_name = basename(dir_name)
  if(length(tsvs) == 1){
    tsv_file = readr::read_tsv(tsvs, comment = "##") %>% janitor::clean_names()
    toi = tsv_file %>%
    tidyr::unite(col = 'uid', c(genes,coding,amino_acid_change,locus), remove = FALSE, sep = "__") %>%
    dplyr::select(uid, homopolymer_length,ref_ref_var_var,phred_qual_score,coverage,ucsc_common_sn_ps)
      toi$name = base_name
      extract_tif = extract_parameters_from_dirname(toi$name)
      tiffo = dplyr::left_join(toi, extract_tif) %>% dplyr::distinct()
      return(tiffo)
  }
}

```

## Loop over all entries
```{r}
complete_list = list()

for (i in seq_along(preps)){
  snv_path_1 = as.character(preps[i])
  #f_total = dplyr::bind_rows(f1, f2)
  complete_table = snv_read(snv_path_1)
  complete_list[[i]] = complete_table
}
```



##  
```{r}
complete_list = lapply(complete_list, function(x) x %>% dplyr::mutate_all(as.character))
```


```{r}
complete_tbl = dplyr::bind_rows(complete_list)
```


```{r}
complete_table = add_coordinates(complete_tbl)
```


```{r}
param_df = extract_parameters_from_dirname(complete_table$name)
```


```{r}
comp_tbl = dplyr::left_join(complete_table, param_df) %>% dplyr::distinct()
```

## Add variant metrics
```{r, include=FALSE}
# detailed exports
tifs = lapply(preps, read_input_tsv)
```


```{r, include=FALSE}
tifs = tifs[which(!unlist(lapply(tifs, is.null)))]
tifs = lapply(tifs, function(x) x %>% dplyr::mutate_all(as.character))
tifs = dplyr::bind_rows(tifs)
```


```{r, include=FALSE}
compl = dplyr::left_join(comp_tbl, tifs,by = c('uid','name'))
readr::write_tsv(comp_tbl, paste0(diroi,"/Complete_variant_list_filename.tsv"))

count_variants = dplyr::group_by(comp_tbl,uid) %>%
  dplyr::count(sort = TRUE) %>%
  dplyr::filter(n>1)
```




```{r, include=FALSE}
variants_parameters = dplyr::left_join(count_variants, compl) %>%
  dplyr::select(chr, start, end, gene,coding, amino_acid_change, locus, homopolymer_length,ref_ref_var_var,phred_qual_score,coverage,ucsc_common_sn_ps, pcr_id.y, Bno.y)
```
```{r}
DT::datatable(variants_parameters)
```

```{r, include=FALSE}
readr::write_tsv(count_variants, paste0(diroi,"/Counted_variants.tsv"))
readr::write_tsv(variants_parameters, paste0(diroi,"/variants_parameters.tsv"))
```
